version: '3'

services:
  db:
    image: postgres

    environment: 
      POSTGRES_DB: cleantemplate
      POSTGRES_USER: mezdelex
      POSTGRES_PASSWORD: mezdelex
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./Docker/.containers/database:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management

    environment:
      RABBITMQ_DEFAULT_USER: mezdelex
      RABBITMQ_DEFAULT_PASS: mezdelex
    hostname: clean-rabbit
    ports:
      # AMQP protocol port
      - 5672:5672
      # HTTP management UI
      - 15672:15672
    restart: always
    volumes:
      - ./Docker/.containers/queue/data/:/var/lib/rabbitmq
      - ./Docker/.containers/queue/log/:/var/log/rabbitmq
